# -*- coding: utf-8 -*-
"""stackoverflowapi.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wARdHrXG6CB7aerrym2twzC-WnG6NZ5F
"""

import requests

import pandas as pd

import json

link="https://api.stackexchange.com/2.2/"
method="questions?"
page=1
pagesize=100
fromdate="1564617600"
todate="1567209600"
order="desc"
sort="creation"
tagged="bigdata"
site="stackoverflow"
filter1="!OfZM.T7UfeY0lN*luvxIpen_tIa6VtNPI*Iyo6tDOrL"

type(todate)

call=link+method+"page="+str(page)+"&pagesize="+str(pagesize)+"&fromdate="+fromdate+"&todate="+todate+"&order="+order+"&sort="+sort+"&tagged="+tagged+"&site="+site+"&filter="+filter1

call

firstdata=requests.get(call)

firstjson=firstdata.json()

firstjson

first_hasmore=firstjson["has_more"]

type(first_hasmore)

tempjson=firstjson["items"]

tempjson[4]["answer_count"]

if(first_hasmore):
    while(first_hasmore):
        page+=1
        call=link+method+"page="+str(page)+"&pagesize="+str(pagesize)+"&fromdate="+fromdate+"&todate="+todate+"&order="+order+"&sort="+sort+"&tagged="+tagged+"&site="+site+"&filter="+filter1
        tempdata=requests.get(call)
        tempjson2=tempdata.json()
        tempjson+=tempjson2["items"]
        first_hasmore=tempjson2["has_more"]
    df=pd.DataFrame(tempjson)
    df.to_csv("newstackdata.csv")
            
else:
    
    df=pd.DataFrame(tempjson)
    df.to_csv("newstackdata.csv")

tempanswer=[]

tempjson

len(tempjson)

for i in range(len(tempjson)):
    
    if((tempjson[i]["answer_count"]) != 0):
        tempanswer += tempjson[i]["answers"]
        del tempjson[i]["answers"]



tempjson[1]



tempjson



with open('newstackquestions.json', 'w') as json_file:
    json.dump(tempjson, json_file)
    
    
with open('newstackanswers.json', 'w') as json_file:
    json.dump(tempanswer, json_file)

dfquestions=pd.read_json("newstackquestions.json")
dfanswers=pd.read_json("newstackanswers.json")

dfquestions.to_csv("newstackquestions.csv",index=False)
dfanswers.to_csv("newstackanswers.csv",index=False)

import xlsxwriter

dfquestions.to_excel('newstackquestions.xlsx', engine='xlsxwriter',index=False) 
dfanswers.to_excel('newstackanswers.xlsx', engine='xlsxwriter',index=False)